"""add props

Revision ID: 142cfd436f29
Revises: cc122cc2bd0a
Create Date: 2025-10-04 13:30:16.779762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '142cfd436f29'
down_revision: Union[str, Sequence[str], None] = 'cc122cc2bd0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('battery', sa.Column('props', sa.JSON(), nullable=True))
    op.add_column('device', sa.Column('props', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('device', 'props')
    op.drop_column('battery', 'props')
    # ### end Alembic commands ###
