"""add props tr

Revision ID: e378746743eb
Revises: 142cfd436f29
Create Date: 2025-10-04 13:42:49.380639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e378746743eb'
down_revision: Union[str, Sequence[str], None] = '142cfd436f29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('battery', sa.Column('props_tr', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('battery', 'props_tr')
    # ### end Alembic commands ###
